namespace: "homefriend"

hub:
  deployment: "madworldnl-hub-deployment"
  app: "madworldnl-hub"
  name: "hub"
  loadBalancer: "madworldnl-hub-loadbalancer"
  image: "ghcr.io/madworldnl/homefriend-hub"
  tag: "latest"
  host: "hub.localhost"
  
portal:
  deployment: "madworldnl-portal-deployment"
  app: "madworldnl-portal"
  name: "portal"
  loadBalancer: "madworldnl-portal-loadbalancer"
  image: "ghcr.io/madworldnl/homefriend-portal"
  tag: "latest"
  host: "portal.localhost"
  
ingress:
  name: "madworldnl-ingress"
  
hosts:
  name: "madworldnl-hosts"