namespace: "homefriend"

hub:
  deployment: "madworldnl-hub-deployment"
  app: "madworldnl-hub"
  name: "hub"
  loadBalancer: "madworldnl-hub-loadbalancer"
  image: "ghcr.io/madworldnl/homefriend-hub"
  tag: "latest"
  host: "hub.localhost"
  
portal:
  deployment: "madworldnl-portal-deployment"
  app: "madworldnl-portal"
  name: "portal"
  loadBalancer: "madworldnl-portal-loadbalancer"
  image: "ghcr.io/madworldnl/homefriend-portal"
  tag: "latest"
  host: "portal.localhost"
  
postgresql:
  app: "madworldnl-postgresql"
  cluster: "madworldnl-postgresql-cluster"
  name: "postgresql"
  
ingress:
  name: "madworldnl-ingress"
  
hosts:
  name: "madworldnl-hosts"
  
secrets:
  name:
    superuser: "postgresql-superuser-secret"
    app: "postgresql-app-secret"