apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.portal.host }}
      http:
        paths:
          # All the path will be directed to the SPA application
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.portal.loadBalancer }}
                port:
                  number: 80
    - host: {{ .Values.hub.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.hub.loadBalancer }}
                port:
                  number: 80