apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: {{ .Values.portal.host }}
      http:
        paths:
        # All the path will be directed to the SPA application
        - path: "/(.*(?:css|css.map|html|js|json|png|txt|wasm|dat)$)|(.*)"
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ .Values.portal.loadBalancer }}
              port:
                number: 80
    - host: {{ .Values.hub.host }}
      http:
        paths:
          - path: "/(.*)"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.hub.loadBalancer }}
                port:
                  number: 80