{{- $superuserSecret := (lookup "v1" "Secret" .Values.namespace .Values.secrets.name.superuser ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name.superuser }}
  namespace: {{ .Values.namespace }}
data:
  {{ if $superuserSecret -}}
  username: {{ $superuserSecret.data.username }}
  password: {{ $superuserSecret.data.password }}
  {{ else -}}
  username: {{ "god" | b64enc }}
  password: {{ "passwordV3" | b64enc }}
  {{ end }}
type: kubernetes.io/basic-auth
---
{{- $appSecret := (lookup "v1" "Secret" .Values.namespace .Values.secrets.name.app) -}}
apiVersion: v1
kind: Secret
data:
  {{ if $appSecret -}}
  username: {{ $appSecret.data.username }}
  password: {{ $appSecret.data.password }}
  {{ else -}}
  username: {{ "app" | b64enc }}
  password: {{ "passwordV3" | b64enc }}
  {{ end }}
metadata:
  name: {{ .Values.secrets.name.app }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.postgresql.cluster }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.postgresql.app }}
    name: {{ .Values.postgresql.name }}
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:13.6

  superuserSecret:
    name: {{ .Values.secrets.name.superuser }}
    
  bootstrap:
    initdb:
      database: MadWorldNL
      owner: app
      secret:
        name: {{ .Values.secrets.name.app }}
  
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
      volumeMode: Filesystem
  walStorage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
      volumeMode: Filesystem