apiVersion: v1
metadata:
  name: {{ .Values.secrets.name.superuser }}
  namespace: {{ .Values.namespace }}
data:
  username: Z29k
  password: cGFzc3dvcmQ=
kind: Secret
type: kubernetes.io/basic-auth
---
apiVersion: v1
data:
  username: YXBw
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: {{ .Values.secrets.name.app }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.postgresql.cluster }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.postgresql.app }}
    name: {{ .Values.postgresql.name }}
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:13.6

  superuserSecret:
    name: {{ .Values.secrets.name.superuser }}
    
  bootstrap:
    initdb:
      database: MadWorldNL
      owner: app
      secret:
        name: {{ .Values.secrets.name.app }}
  
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
      volumeMode: Filesystem
    walStorage:
      pvcTemplate:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
        volumeMode: Filesystem